# Generated by Django 5.0.7 on 2025-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(help_text='El término químico.', max_length=255, unique=True)),
                ('definition', models.TextField(help_text='La definición del término.')),
            ],
            options={
                'verbose_name': 'Término del Glosario',
                'verbose_name_plural': 'Términos del Glosario',
                'ordering': ['term'],
            },
        ),
    ]
