# Generated by Django 5.0.7 on 2025-07-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryterm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='updated_at',
        ),
    ]
