# Generated by Django 5.0.7 on 2025-07-27 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_remove_glossaryterm_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
