# Generated by Django 5.0.7 on 2025-08-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_glossaryterm_created_at_glossaryterm_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.'),
        ),
    ]
