# Generated by Django 5.0.7 on 2025-08-19 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_alter_glossaryterm_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PHCalculationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('ph_to_all', 'pH a todas las variables'), ('concentration_to_ph', 'Concentración a pH'), ('buffer_calculation', 'Cálculo de buffer'), ('ionic_strength', 'Cálculo de fuerza iónica'), ('activity_correction', 'Corrección de actividad')], help_text='Tipo de cálculo realizado', max_length=50)),
                ('input_data', models.JSONField(help_text='Datos de entrada validados en formato JSON')),
                ('results', models.JSONField(help_text='Todos los resultados calculados en formato JSON')),
                ('calculation_steps', models.JSONField(blank=True, help_text='Pasos detallados del cálculo (opcional)', null=True)),
                ('warnings', models.JSONField(default=list, help_text='Warnings generados durante el cálculo')),
                ('temperature', models.FloatField(default=25.0, help_text='Temperatura del cálculo en °C')),
                ('ionic_strength', models.FloatField(blank=True, help_text='Fuerza iónica del sistema en mol/L', null=True)),
                ('calculation_time_ms', models.IntegerField(help_text='Tiempo de cálculo en milisegundos')),
            ],
            options={
                'verbose_name': 'Historial de Cálculo de pH',
                'verbose_name_plural': 'Historial de Cálculos de pH',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='glossaryterm',
            index=models.Index(fields=['term'], name='calculators_term_c52e14_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryterm',
            index=models.Index(fields=['created_at'], name='calculators_created_bbda67_idx'),
        ),
        migrations.AddField(
            model_name='phcalculationhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cálculo (null para usuarios anónimos)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='phcalculationhistory',
            index=models.Index(fields=['user'], name='calculators_user_id_1a0c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='phcalculationhistory',
            index=models.Index(fields=['calculation_type'], name='calculators_calcula_6471ac_idx'),
        ),
        migrations.AddIndex(
            model_name='phcalculationhistory',
            index=models.Index(fields=['created_at'], name='calculators_created_a4a6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='phcalculationhistory',
            index=models.Index(fields=['user', 'calculation_type'], name='calculators_user_id_c3c95a_idx'),
        ),
    ]
