# Generated by Django 5.0.7 on 2025-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_phcalculationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('code', models.CharField(help_text='Código único del sistema buffer', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre del sistema buffer', max_length=200)),
                ('acid_formula', models.CharField(help_text='Fórmula del ácido', max_length=100)),
                ('base_formula', models.CharField(help_text='Fórmula de la base conjugada', max_length=100)),
                ('pka', models.FloatField(help_text='pKa del ácido')),
                ('effective_ph_min', models.FloatField(help_text='pH mínimo efectivo del buffer')),
                ('effective_ph_max', models.FloatField(help_text='pH máximo efectivo del buffer')),
                ('optimal_ph', models.FloatField(help_text='pH óptimo del buffer (generalmente igual al pKa)')),
                ('common_uses', models.TextField(blank=True, help_text='Usos comunes de este sistema buffer')),
                ('preparation_notes', models.TextField(blank=True, help_text='Notas sobre la preparación del buffer')),
                ('is_active', models.BooleanField(default=True, help_text='Si el sistema buffer está activo')),
                ('usage_count', models.IntegerField(default=0, help_text='Contador de veces que se ha usado')),
            ],
            options={
                'verbose_name': 'Sistema Buffer',
                'verbose_name_plural': 'Sistemas Buffer',
                'ordering': ['pka', 'name'],
                'indexes': [models.Index(fields=['code'], name='calculators_code_dfa14d_idx'), models.Index(fields=['pka'], name='calculators_pka_3bb0a1_idx'), models.Index(fields=['is_active'], name='calculators_is_acti_eb74e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChemicalPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('code', models.CharField(help_text='Código único del preset (ej: hcl_0.1)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del preset', max_length=200)),
                ('category', models.CharField(choices=[('strong_acid', 'Ácido Fuerte'), ('strong_base', 'Base Fuerte'), ('weak_acid', 'Ácido Débil'), ('weak_base', 'Base Débil'), ('buffer', 'Sistema Buffer'), ('physiological', 'Fisiológico'), ('industrial', 'Industrial'), ('educational', 'Educacional')], help_text='Categoría del preset', max_length=20)),
                ('description', models.TextField(help_text='Descripción detallada del preset y su uso')),
                ('chemical_formula', models.CharField(blank=True, help_text='Fórmula química (ej: HCl, NaOH, CH₃COOH)', max_length=100)),
                ('calculation_type', models.CharField(choices=[('concentration_to_ph', 'Concentración → pH'), ('ph_to_all', 'pH → Todas las variables'), ('buffer_calculation', 'Cálculo de Buffer')], help_text='Tipo de cálculo predefinido', max_length=30)),
                ('calculation_values', models.JSONField(default=dict, help_text='Valores predefinidos para el cálculo')),
                ('is_active', models.BooleanField(default=True, help_text='Si el preset está activo y disponible')),
                ('usage_count', models.IntegerField(default=0, help_text='Contador de veces que se ha usado este preset')),
                ('difficulty_level', models.IntegerField(default=1, help_text='Nivel de dificultad (1=Básico, 2=Intermedio, 3=Avanzado)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para búsqueda y categorización')),
            ],
            options={
                'verbose_name': 'Preset Químico',
                'verbose_name_plural': 'Presets Químicos',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['code'], name='calculators_code_b4ffcb_idx'), models.Index(fields=['category'], name='calculators_categor_278f5e_idx'), models.Index(fields=['is_active'], name='calculators_is_acti_b94f68_idx')],
            },
        ),
    ]
