# Generated by Django 5.0.7 on 2025-08-31 23:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('method_type', models.CharField(choices=[('mechanical', 'Mecánico'), ('physical', 'Físico'), ('chemical', 'Químico'), ('magnetic', 'Magnético'), ('thermal', 'Térmico')], max_length=20)),
                ('description', models.TextField()),
                ('principle', models.TextField(help_text='Principio físico/químico')),
                ('equipment_required', models.JSONField(default=list, help_text='Lista de equipos necesarios')),
                ('conditions_required', models.JSONField(default=dict, help_text='Condiciones necesarias (temp, presión, pH, etc.)')),
                ('efficiency_range', models.JSONField(default=dict, help_text='Rango de eficiencia {min: %, max: %}')),
                ('cost_factor', models.IntegerField(help_text='Factor de costo (1=barato, 5=caro)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('complexity_level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('applicable_phases', models.JSONField(default=list, help_text='Fases aplicables')),
                ('property_criteria', models.JSONField(default=dict, help_text='Criterios de propiedades (tamaño, densidad, etc.)')),
            ],
            options={
                'verbose_name': 'Método de Separación',
                'verbose_name_plural': 'Métodos de Separación',
                'ordering': ['method_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('formula', models.CharField(db_index=True, max_length=50)),
                ('cas_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('molecular_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('density', models.FloatField(help_text='Densidad en g/cm³', validators=[django.core.validators.MinValueValidator(0)])),
                ('melting_point', models.FloatField(blank=True, help_text='Punto de fusión en °C', null=True)),
                ('boiling_point', models.FloatField(blank=True, help_text='Punto de ebullición en °C', null=True)),
                ('solubility_water', models.FloatField(blank=True, help_text='Solubilidad en agua en g/L a 25°C', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('magnetic_susceptibility', models.FloatField(blank=True, help_text='Susceptibilidad magnética en emu/g', null=True)),
                ('particle_size_range', models.JSONField(default=dict, help_text='Rango de tamaño de partícula {min: μm, max: μm}')),
                ('phase_at_stp', models.CharField(choices=[('solid', 'Sólido'), ('liquid', 'Líquido'), ('gas', 'Gas')], db_index=True, max_length=10)),
                ('chemical_category', models.CharField(choices=[('organic', 'Orgánico'), ('inorganic', 'Inorgánico'), ('metal', 'Metal'), ('salt', 'Sal'), ('oxide', 'Óxido'), ('acid', 'Ácido'), ('base', 'Base'), ('mineral', 'Mineral')], db_index=True, max_length=20)),
                ('safety_data', models.JSONField(default=dict, help_text='Datos de seguridad (toxicidad, inflamabilidad, etc.)')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sustancia Química',
                'verbose_name_plural': 'Sustancias Químicas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['phase_at_stp', 'chemical_category'], name='systems_ana_phase_a_6f81cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solubility_organic', models.JSONField(default=dict, help_text='Solubilidad en solventes orgánicos')),
                ('vapor_pressure', models.FloatField(blank=True, help_text='Presión de vapor en mmHg a 25°C', null=True)),
                ('refractive_index', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, help_text='Conductividad en S/m', null=True)),
                ('hardness_mohs', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('crystal_system', models.CharField(blank=True, max_length=50)),
                ('surface_tension', models.FloatField(blank=True, help_text='Tensión superficial en mN/m', null=True)),
                ('viscosity', models.FloatField(blank=True, help_text='Viscosidad en cP', null=True)),
                ('thermal_conductivity', models.FloatField(blank=True, help_text='Conductividad térmica en W/m·K', null=True)),
                ('specific_heat', models.FloatField(blank=True, help_text='Calor específico en J/g·K', null=True)),
                ('substance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_properties', to='systems_analysis.chemicalsubstance')),
            ],
            options={
                'verbose_name': 'Base de Datos de Propiedades',
                'verbose_name_plural': 'Bases de Datos de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='SystemAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('analysis_data', models.JSONField(default=dict)),
                ('system_type', models.CharField(choices=[('heterogeneous', 'Heterogéneo'), ('homogeneous', 'Homogéneo'), ('colloidal', 'Coloidal')], db_index=True, max_length=20)),
                ('phases_detected', models.JSONField(default=list, help_text='Lista de fases detectadas')),
                ('total_mass', models.FloatField(help_text='Masa total del sistema en gramos', validators=[django.core.validators.MinValueValidator(0)])),
                ('analysis_temperature', models.FloatField(default=25.0, help_text='Temperatura de análisis en °C')),
                ('analysis_pressure', models.FloatField(default=1.0, help_text='Presión de análisis en atm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Sistema',
                'verbose_name_plural': 'Análisis de Sistemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparationProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=200)),
                ('separation_steps', models.JSONField(default=list, help_text='Secuencia ordenada de métodos')),
                ('predicted_efficiency', models.FloatField(help_text='Eficiencia predicha en %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_time', models.FloatField(help_text='Tiempo estimado en horas', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cost', models.FloatField(help_text='Costo relativo (escala 1-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty_level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('final_products', models.JSONField(default=list, help_text='Productos finales esperados')),
                ('process_diagram', models.JSONField(default=dict, help_text='Datos para visualización del diagrama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_processes', to='systems_analysis.systemanalysis')),
            ],
            options={
                'verbose_name': 'Proceso de Separación',
                'verbose_name_plural': 'Procesos de Separación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_fraction', models.FloatField(help_text='Fracción másica (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('volume_fraction', models.FloatField(blank=True, help_text='Fracción volumétrica (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('phase', models.CharField(choices=[('solid', 'Sólido'), ('liquid', 'Líquido'), ('gas', 'Gas'), ('dissolved', 'Disuelto'), ('suspended', 'Suspendido'), ('emulsified', 'Emulsionado')], max_length=20)),
                ('particle_size', models.FloatField(blank=True, help_text='Tamaño de partícula en μm', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_dispersed', models.BooleanField(default=False)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems_analysis.chemicalsubstance')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems_analysis.systemanalysis')),
            ],
            options={
                'ordering': ['-mass_fraction'],
                'unique_together': {('system', 'substance')},
            },
        ),
        migrations.AddField(
            model_name='systemanalysis',
            name='components',
            field=models.ManyToManyField(related_name='in_systems', through='systems_analysis.SystemComponent', to='systems_analysis.chemicalsubstance'),
        ),
        migrations.AddIndex(
            model_name='systemanalysis',
            index=models.Index(fields=['user', '-created_at'], name='systems_ana_user_id_23abaf_idx'),
        ),
        migrations.AddIndex(
            model_name='systemanalysis',
            index=models.Index(fields=['system_type'], name='systems_ana_system__a598dc_idx'),
        ),
    ]
