# Generated by Django 5.0.7 on 2025-08-10 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('options', models.JSONField(help_text='Array de 4 opciones', verbose_name='Opciones')),
                ('correct_option', models.IntegerField(help_text='Índice de la opción correcta (0-3)', verbose_name='Opción correcta')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicación')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('nomenclature', 'Nomenclatura'), ('periodic_table', 'Tabla Periódica'), ('reactions', 'Reacciones Químicas'), ('atomic_structure', 'Estructura Atómica'), ('lewis_structures', 'Estructuras de Lewis'), ('solutions', 'Disoluciones'), ('ph_calculations', 'Cálculos de pH')], max_length=20)),
                ('points', models.IntegerField(default=10, verbose_name='Puntos')),
            ],
            options={
                'verbose_name': 'Pregunta de Quiz',
                'verbose_name_plural': 'Preguntas de Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('best_score', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('fastest_completion', models.IntegerField(blank=True, null=True, verbose_name='Tiempo más rápido (segundos)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Clasificación',
                'verbose_name_plural': 'Tablas de Clasificación',
                'ordering': ['-best_score', 'fastest_completion'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('questions', models.JSONField(help_text='Array de IDs de preguntas', verbose_name='IDs de preguntas')),
                ('current_question_index', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_limit_seconds', models.IntegerField(default=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Quiz',
                'verbose_name_plural': 'Sesiones de Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('selected_option', models.IntegerField(verbose_name='Opción seleccionada')),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(verbose_name='Tiempo en segundos')),
                ('points_earned', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.quizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.quizsession')),
            ],
            options={
                'verbose_name': 'Respuesta de Quiz',
                'verbose_name_plural': 'Respuestas de Quiz',
            },
        ),
    ]
