# Generated by Django 5.0.7 on 2025-08-10 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('word', models.CharField(max_length=20, unique=True, verbose_name='Palabra')),
                ('word_lower', models.CharField(db_index=True, max_length=20, verbose_name='Palabra en minúsculas')),
                ('category', models.CharField(choices=[('element', 'Elemento'), ('compound', 'Compuesto'), ('ion', 'Ion'), ('molecule', 'Molécula')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('hint', models.TextField(verbose_name='Pista principal')),
                ('atomic_number', models.IntegerField(blank=True, null=True, verbose_name='Número atómico')),
                ('group_number', models.IntegerField(blank=True, null=True, verbose_name='Grupo')),
                ('period_number', models.IntegerField(blank=True, null=True, verbose_name='Período')),
                ('state_at_stp', models.CharField(blank=True, max_length=10, verbose_name='Estado a STP')),
                ('chemical_formula', models.CharField(blank=True, max_length=50, verbose_name='Fórmula química')),
                ('molecular_weight', models.FloatField(blank=True, null=True, verbose_name='Peso molecular')),
                ('hints_progressive', models.JSONField(default=list, verbose_name='Pistas progresivas')),
                ('times_used', models.IntegerField(default=0, verbose_name='Veces usada')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Tasa de éxito')),
            ],
            options={
                'verbose_name': 'Palabra Química',
                'verbose_name_plural': 'Palabras Químicas',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ChemWordleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('attempts_used', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=6)),
                ('guesses', models.JSONField(default=list, verbose_name='Intentos realizados')),
                ('hints_revealed', models.JSONField(default=list, verbose_name='Pistas reveladas')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.chemicalword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida ChemWordle',
                'verbose_name_plural': 'Partidas ChemWordle',
                'unique_together': {('user', 'target_word', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='ChemWordleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('win_distribution', models.JSONField(default=dict)),
                ('best_time_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas ChemWordle',
                'verbose_name_plural': 'Estadísticas ChemWordle',
            },
        ),
        migrations.CreateModel(
            name='ChemWordleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('attempt_number', models.IntegerField(verbose_name='Número de intento')),
                ('guessed_word', models.CharField(max_length=20, verbose_name='Palabra adivinada')),
                ('letter_results', models.JSONField(verbose_name='Resultado por letra')),
                ('time_taken_seconds', models.IntegerField(verbose_name='Tiempo en segundos')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.chemwordlegame')),
            ],
            options={
                'verbose_name': 'Intento ChemWordle',
                'verbose_name_plural': 'Intentos ChemWordle',
                'ordering': ['attempt_number'],
                'unique_together': {('game', 'attempt_number')},
            },
        ),
    ]
