# Generated by Django 5.0.7 on 2025-08-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_chemicalword_chemwordlegame_chemwordlestats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('pairs_found', models.IntegerField(default=0)),
                ('total_pairs', models.IntegerField(default=6)),
                ('attempts', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('cards_data', models.JSONField(verbose_name='Datos de las cartas')),
                ('revealed_pairs', models.JSONField(default=list, verbose_name='Pares revelados')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida Memory Molecular',
                'verbose_name_plural': 'Partidas Memory Molecular',
            },
        ),
        migrations.CreateModel(
            name='MemoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('games_played', models.IntegerField(default=0)),
                ('games_completed', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('best_time_easy', models.IntegerField(blank=True, null=True)),
                ('best_time_medium', models.IntegerField(blank=True, null=True)),
                ('best_time_hard', models.IntegerField(blank=True, null=True)),
                ('total_pairs_found', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas Memory Molecular',
                'verbose_name_plural': 'Estadísticas Memory Molecular',
            },
        ),
    ]
