# Generated by Django 5.0.7 on 2025-08-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_memorygame_memorystats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceChallengeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('original_equation', models.TextField(verbose_name='Ecuación original')),
                ('target_balanced_equation', models.TextField(verbose_name='Ecuación balanceada objetivo')),
                ('target_coefficients', models.JSONField(verbose_name='Coeficientes objetivo')),
                ('user_coefficients', models.JSONField(default=dict, verbose_name='Coeficientes del usuario')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('hints_used', models.JSONField(default=list, verbose_name='Pistas utilizadas')),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafío de Balanceo',
                'verbose_name_plural': 'Desafíos de Balanceo',
            },
        ),
        migrations.CreateModel(
            name='BalanceChallengeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('games_played', models.IntegerField(default=0)),
                ('games_completed', models.IntegerField(default=0)),
                ('games_correct', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('easy_completed', models.IntegerField(default=0)),
                ('easy_correct', models.IntegerField(default=0)),
                ('medium_completed', models.IntegerField(default=0)),
                ('medium_correct', models.IntegerField(default=0)),
                ('hard_completed', models.IntegerField(default=0)),
                ('hard_correct', models.IntegerField(default=0)),
                ('average_time_per_game', models.FloatField(default=0.0)),
                ('best_time_easy', models.IntegerField(blank=True, null=True)),
                ('best_time_medium', models.IntegerField(blank=True, null=True)),
                ('best_time_hard', models.IntegerField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas de Balanceo',
                'verbose_name_plural': 'Estadísticas de Balanceo',
            },
        ),
        migrations.CreateModel(
            name='BalanceChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('attempt_number', models.IntegerField(verbose_name='Número de intento')),
                ('coefficients_submitted', models.JSONField(verbose_name='Coeficientes enviados')),
                ('is_correct', models.BooleanField(default=False)),
                ('validation_result', models.JSONField(verbose_name='Resultado de validación')),
                ('time_taken_seconds', models.IntegerField(verbose_name='Tiempo en segundos')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_history', to='games.balancechallengegame')),
            ],
            options={
                'verbose_name': 'Intento de Balanceo',
                'verbose_name_plural': 'Intentos de Balanceo',
                'ordering': ['attempt_number'],
                'unique_together': {('game', 'attempt_number')},
            },
        ),
    ]
