# Generated by Django 5.0.7 on 2025-08-10 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_balancechallengegame_balancechallengestats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicSpeedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('target_element', models.JSONField(verbose_name='Elemento objetivo')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.FloatField(blank=True, null=True)),
                ('selected_element', models.JSONField(blank=True, null=True, verbose_name='Elemento seleccionado')),
                ('hint_used', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juego de Velocidad Periódica',
                'verbose_name_plural': 'Juegos de Velocidad Periódica',
            },
        ),
        migrations.CreateModel(
            name='PeriodicSpeedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.')),
                ('games_played', models.IntegerField(default=0)),
                ('games_correct', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('best_time_seconds', models.FloatField(blank=True, null=True)),
                ('average_time_seconds', models.FloatField(default=0.0)),
                ('total_time_seconds', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('metals_correct', models.IntegerField(default=0)),
                ('nonmetals_correct', models.IntegerField(default=0)),
                ('metalloids_correct', models.IntegerField(default=0)),
                ('noble_gases_correct', models.IntegerField(default=0)),
                ('best_time_metals', models.FloatField(blank=True, null=True)),
                ('best_time_nonmetals', models.FloatField(blank=True, null=True)),
                ('best_time_metalloids', models.FloatField(blank=True, null=True)),
                ('best_time_noble_gases', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas de Velocidad Periódica',
                'verbose_name_plural': 'Estadísticas de Velocidad Periódica',
            },
        ),
    ]
