"""
Django settings for chems_tools project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
import os 
import sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ap11g%4tgv50-cf3bl(6+u8x2$e7s=jax4gxo^@j+nj-9)zqty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '*']  # '*' permite cualquier host (cambiar en producción)

# Enable APPEND_SLASH for Django REST Framework routers
APPEND_SLASH = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Local Apps
    'api',
    
    # core app for custom utilities
    'core',
    
    # users app for custom user model
    'users.apps.UsersConfig',
    
    # for API documentation
    'drf_spectacular',  
    
    # molecules app
    'molecules.apps.MoleculesConfig',
    
    # telemetry app for tracking usage
    'telemetry.apps.TelemetryConfig',
    
    # calculators app for chemical calculations
    'calculators.apps.CalculatorsConfig',
    
    # structures app for handling chemical structures
    'structures',
    
    # reactions app for chemical reactions
    'reactions',
    
    # games app for quiz and other games
    'games.apps.GamesConfig',
    
    # monitoring app for metrics and health checks
    'monitoring',
]

AUTH_USER_MODEL = 'users.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # middleware de CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chems_tools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chems_tools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'chemstools_db',
        'USER': 'chemstools_user',
        'PASSWORD': 'chemstools_password',
        'HOST': 'localhost',
        'PORT': 5432,
    }
}

# If the DATABASE_URL environment variable is set, use it to configure the database.
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Permitir peticiones desde frontend
    "http://127.0.0.1:3000",
    "http://localhost:80",   # Nginx local
    "http://127.0.0.1:80",   # Nginx local
    "http://localhost",       # Sin puerto
    "http://127.0.0.1",       # Sin puerto
]

# Función para permitir orígenes dinámicos (útil para IPs de red local)
def cors_allow_particular_origins(origin):
    """Permite orígenes de la red local"""
    allowed_patterns = [
        r'^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 192.168.x.x
        r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 10.x.x.x
        r'^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 172.16-31.x.x
        r'^http://localhost(:\d+)?$',  # localhost con cualquier puerto
        r'^http://127\.0\.0\.1(:\d+)?$',  # 127.0.0.1 con cualquier puerto
    ]
    import re
    for pattern in allowed_patterns:
        if re.match(pattern, origin):
            return True
    return False

# Usar el callback para verificación dinámica de orígenes
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 192.168.x.x
    r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 10.x.x.x
    r'^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}(:\d+)?$',  # Red local 172.16-31.x.x
]

# Permitir credenciales en las peticiones CORS
CORS_ALLOW_CREDENTIALS = True

# Headers permitidos en las peticiones CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Para desarrollo: permitir todos los orígenes (cambiar en producción)
# CORS_ALLOW_ALL_ORIGINS = True  # ¡Solo para desarrollo!

# test settings 
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

# REST Framework settings
# Configuración de autenticación JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Añadir esta nueva sección para el rate limiting
    # TEMPORALMENTE DESACTIVADO PARA PRUEBAS
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ],
    # # Configuración de los límites de rate limiting
    # # Límite de peticiones por día para usuarios anónimos y autenticados
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/day', # Límite para usuarios anónimos
    #     'user': '1000/day', # Límite para usuarios autenticados
    #     'auth': '5/min', # Límite estricto para login/registro
    # },
    # Configuración de paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10 # Número de items por página
}

SPECTACULAR_SETTINGS = { 'TITLE': 'ChemsTools API' }

# Logging configuration
# Configuración de logging para registrar información en consola y archivo
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "chemstools"
    }
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}
