# Generated by Django 5.0.7 on 2025-08-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_equation', models.TextField(help_text='Ecuación química original no balanceada')),
                ('balanced_equation', models.TextField(help_text='Ecuación química balanceada')),
                ('coefficients', models.JSONField(help_text='Coeficientes de balanceo')),
                ('reaction_type', models.CharField(blank=True, help_text='Tipo de reacción (síntesis, descomposición, combustión)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reacción Balanceada',
                'verbose_name_plural': 'Reacciones Balanceadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
