# Generated by Django 5.0.7 on 2025-08-09 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(db_index=True, max_length=100)),
                ('mol_data', models.TextField(help_text='MOL format data')),
                ('lewis_data', models.JSONField(help_text='Lewis structure JSON representation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('formula',)},
            },
        ),
    ]
