# Generated by Django 5.0.7 on 2025-08-12 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='Query original (nombre, fórmula, etc)', max_length=500)),
                ('query_type', models.CharField(choices=[('name', 'Nombre común'), ('iupac', 'Nombre IUPAC'), ('smiles', 'SMILES'), ('formula', 'Fórmula molecular'), ('inchi', 'InChI'), ('cas', 'CAS Number')], help_text='Tipo de query utilizado', max_length=50)),
                ('smiles', models.CharField(help_text='SMILES canónico del compuesto', max_length=1000)),
                ('iupac_name', models.CharField(blank=True, help_text='Nombre IUPAC oficial', max_length=1000, null=True)),
                ('common_names', models.JSONField(default=list, help_text='Lista de nombres comunes y sinónimos')),
                ('molecular_formula', models.CharField(help_text='Fórmula molecular', max_length=200)),
                ('molecular_weight', models.FloatField(blank=True, help_text='Peso molecular', null=True)),
                ('pubchem_cid', models.IntegerField(blank=True, help_text='PubChem Compound ID', null=True)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number', max_length=50, null=True)),
                ('inchi', models.TextField(blank=True, help_text='InChI string', null=True)),
                ('inchi_key', models.CharField(blank=True, help_text='InChIKey', max_length=100, null=True)),
                ('properties', models.JSONField(default=dict, help_text='Propiedades adicionales del compuesto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_count', models.IntegerField(default=1, help_text='Número de veces que se ha accedido')),
            ],
            options={
                'ordering': ['-access_count', '-last_accessed'],
                'indexes': [models.Index(fields=['smiles'], name='structures__smiles_67e9a9_idx'), models.Index(fields=['molecular_formula'], name='structures__molecul_39b394_idx'), models.Index(fields=['pubchem_cid'], name='structures__pubchem_982ba8_idx')],
                'unique_together': {('query', 'query_type')},
            },
        ),
    ]
